language: csharp
solution: toy-robot.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore toy-robot.sln
after_script:
  - nunit-console toy-robot-unittest/bin/Release/toy-robot-unittest.dll